CREATE TABLE IF NOT EXISTS `casino_refunds` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `betid` BIGINT UNSIGNED NOT NULL,
    `amount` DECIMAL(32,2) UNSIGNED NOT NULL,
    `time` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `casino_refunds` CHARACTER SET=utf8mb4, COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `casino_refunds` CHANGE COLUMN `id` `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `casino_refunds` CHANGE COLUMN `betid` `betid` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `casino_refunds` CHANGE COLUMN `amount` `amount` DECIMAL(32,2) UNSIGNED NOT NULL;
ALTER TABLE `casino_refunds` CHANGE COLUMN `time` `time` BIGINT UNSIGNED NOT NULL;