ALTER TABLE `paypal_config`
    ADD COLUMN IF NOT EXISTS `payer_id` VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS `email` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS `display_name` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS `access_token` TEXT NULL,
    ADD COLUMN IF NOT EXISTS `refresh_token` TEXT NULL,
    ADD COLUMN IF NOT EXISTS `token_expire` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `connected_at` BIGINT UNSIGNED NOT NULL DEFAULT 0;
