CREATE TABLE IF NOT EXISTS `rain_winnings` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `userid` VARCHAR(36) BINARY NOT NULL,
    `winning` DECIMAL(32,2) UNSIGNED NOT NULL,
    `rainid` BIGINT UNSIGNED NOT NULL,
    `time` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `rain_winnings` CHARACTER SET=utf8mb4, COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `rain_winnings` CHANGE COLUMN `id` `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `rain_winnings` CHANGE COLUMN `userid` `userid` VARCHAR(36) BINARY NOT NULL;
ALTER TABLE `rain_winnings` CHANGE COLUMN `winning` `winning` DECIMAL(32,2) UNSIGNED NOT NULL;
ALTER TABLE `rain_winnings` CHANGE COLUMN `rainid` `rainid` BIGINT UNSIGNED NOT NULL;
ALTER TABLE `rain_winnings` CHANGE COLUMN `time` `time` BIGINT UNSIGNED NOT NULL;