CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bot` BOOLEAN NOT NULL DEFAULT 0,
    `anonymous` BOOLEAN NOT NULL DEFAULT 0,
    `private` BOOLEAN NOT NULL DEFAULT 0,
    `userid` VARCHAR(36) BINARY NOT NULL,
    `email` VARCHAR(255) DEFAULT NULL,
    `password` VARCHAR(64) BINARY DEFAULT NULL,
    `name` VARCHAR(255) NOT NULL,
    `avatar` VARCHAR(2048) NOT NULL,
    `rank` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `balance` DECIMAL(32,5) UNSIGNED NOT NULL DEFAULT 0.00000,
    `xp` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `rollover` DECIMAL(32,2) UNSIGNED NOT NULL DEFAULT 0.00,
    `exclusion` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `time_create` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `UQ_users_userid` (`userid`) USING BTREE,
    UNIQUE INDEX `UQ_users_email` (`email`) USING BTREE,
    INDEX `IX_users_bot` (`bot`) USING BTREE,
    INDEX `IX_users_time_create` (`time_create`) USING BTREE,
    INDEX `IX_users_email_password` (`password`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `users` CHARACTER SET=utf8mb4, COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `users` CHANGE COLUMN `id` `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `users` CHANGE COLUMN `bot` `bot` BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE COLUMN `anonymous` `anonymous` BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE COLUMN `private` `private` BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE COLUMN `userid` `userid` VARCHAR(36) BINARY NOT NULL;
ALTER TABLE `users` CHANGE COLUMN `email` `email` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `users` CHANGE COLUMN `password` `password` VARCHAR(64) BINARY DEFAULT NULL;
ALTER TABLE `users` CHANGE COLUMN `name` `name` VARCHAR(255) NOT NULL;
ALTER TABLE `users` CHANGE COLUMN `avatar` `avatar` VARCHAR(2048) NOT NULL;
ALTER TABLE `users` CHANGE COLUMN `rank` `rank` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE COLUMN `balance` `balance` DECIMAL(32,5) UNSIGNED NOT NULL DEFAULT 0.00000;
ALTER TABLE `users` CHANGE COLUMN `xp` `xp` BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE COLUMN `rollover` `rollover` DECIMAL(32,2) UNSIGNED NOT NULL DEFAULT 0.00;
ALTER TABLE `users` CHANGE COLUMN `exclusion` `exclusion` BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE COLUMN `time_create` `time_create` BIGINT UNSIGNED NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS `UQ_users_userid` ON `users` (`userid`) USING BTREE;
CREATE UNIQUE INDEX IF NOT EXISTS `UQ_users_email` ON `users` (`email`) USING BTREE;

CREATE INDEX IF NOT EXISTS `IX_users_bot` ON `users` (`bot`) USING BTREE;
CREATE INDEX IF NOT EXISTS `IX_users_time_create` ON `users` (`time_create`) USING BTREE;
CREATE INDEX IF NOT EXISTS `IX_users_email_password` ON `users` (`password`) USING BTREE;